info:
  namespace: customcrops
items:
  garlic_stage_1:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/garlic/stage_1
    behaviours:
      furniture:
        entity: item_frame
        shift_interact_rotate: false
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  garlic_stage_2:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/garlic/stage_2
    behaviours:
      furniture:
        entity: item_frame
        shift_interact_rotate: false
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  garlic_stage_3:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/garlic/stage_3
    behaviours:
      furniture:
        entity: item_frame
        shift_interact_rotate: false
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  garlic_stage_4:
    display_name: ""
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/garlic/stage_4
    behaviours:
      furniture:
        entity: item_frame
        shift_interact_rotate: false
        solid: false
        cancel_drop: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  garlic_seeds:
    #display_name: "Garlic Seeds"
    display_name: 大蒜种子
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/garlic/garlic_seeds
  garlic:
    #display_name: "Garlic"
    display_name: 大蒜
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/garlic/garlic
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
  garlic_silver_star:
    #display_name: "Garlic （Silver Star）"
    display_name: 大蒜（银星）
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/garlic/garlic_silver_star
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
  garlic_golden_star:
    #display_name: "Garlic （Golden Star）"
    display_name: 大蒜（金星）
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/garlic/garlic_golden_star
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
categories:
  customcrops_garlic:
    enabled: true
    icon: customcrops:garlic
    name: '大蒜'
    items:
      - customcrops:garlic
      - customcrops:garlic_silver_star
      - customcrops:garlic_golden_star
      - customcrops:garlic_seeds
      - customcrops:garlic_stage_1
      - customcrops:garlic_stage_2
      - customcrops:garlic_stage_3
      - customcrops:garlic_stage_4