info:
  namespace: customcrops
items:
  grape_stage_1:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_1
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_stage_2:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_2
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_stage_3:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_3
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_stage_4:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_4
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_stage_5:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_5
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_stage_6:
    display_name: 葡萄
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/stage_6
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: false
        solid: false
        cancel_drop: false
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  grape_seeds:
    #display_name: ""Grape Seeds"
    display_name: 葡萄种子
    resource:
      generate: false
      material: PAPER
      model_path: item/crops/grape/grape_seeds
  grape:
    #display_name: ""Grape"
    display_name: 葡萄
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/grape/grape
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
  grape_silver_star:
    #display_name: ""Grape (Silver Star)"
    display_name: 葡萄(银星)
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/grape/grape_silver_star
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
  grape_golden_star:
    #display_name: ""Grape (Golden Star)"
    display_name: 葡萄(金星)
    resource:
      generate: false
      material: APPLE
      model_path: item/crops/grape/grape_golden_star
    events:
      eat:
        feed:
          amount: 1
          saturation: 1
categories:
  customcrops_grape:
    enabled: true
    icon: grape
    name: '葡萄'
    items:
      - customcrops:grape_seeds
      - customcrops:grape
      - customcrops:grape_silver_star
      - customcrops:grape_golden_star
      - customcrops:grape_stage_1
      - customcrops:grape_stage_2
      - customcrops:grape_stage_3
      - customcrops:grape_stage_4
      - customcrops:grape_stage_5
      - customcrops:grape_stage_6